import type { Metadata } from "next";
import {
  Archivo,
  Caveat,
  Geist,
  Geist_Mono,
  Open_Sans,
} from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const openSans = Open_Sans({
  variable: "--font-open-sans-family",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "--font-caveat-family",
  subsets: ["latin"],
});

const archivo = Archivo({
  variable: "--font-archivo-family",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${caveat.variable} ${openSans.variable} ${archivo.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
